# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_ui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(620, 460)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(620, 460))
        MainWindow.setMaximumSize(QtCore.QSize(620, 16777215))
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setAnimated(True)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tab = QtGui.QTabWidget(self.centralwidget)
        self.tab.setGeometry(QtCore.QRect(0, 0, 591, 411))
        self.tab.setObjectName(_fromUtf8("tab"))
        self.tabEncrypt = QtGui.QWidget()
        self.tabEncrypt.setObjectName(_fromUtf8("tabEncrypt"))
        self.verticalLayoutWidget_4 = QtGui.QWidget(self.tabEncrypt)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(10, 20, 571, 111))
        self.verticalLayoutWidget_4.setObjectName(_fromUtf8("verticalLayoutWidget_4"))
        self.encAlgorithmsChose = QtGui.QVBoxLayout(self.verticalLayoutWidget_4)
        self.encAlgorithmsChose.setObjectName(_fromUtf8("encAlgorithmsChose"))
        self.enc_radio_des = QtGui.QRadioButton(self.verticalLayoutWidget_4)
        self.enc_radio_des.setObjectName(_fromUtf8("enc_radio_des"))
        self.encAlgorithmsChose.addWidget(self.enc_radio_des)
        self.enc_radio_aes = QtGui.QRadioButton(self.verticalLayoutWidget_4)
        self.enc_radio_aes.setObjectName(_fromUtf8("enc_radio_aes"))
        self.encAlgorithmsChose.addWidget(self.enc_radio_aes)
        self.enc_radio_rsa = QtGui.QRadioButton(self.verticalLayoutWidget_4)
        self.enc_radio_rsa.setObjectName(_fromUtf8("enc_radio_rsa"))
        self.encAlgorithmsChose.addWidget(self.enc_radio_rsa)
        self.encryptButton = QtGui.QPushButton(self.tabEncrypt)
        self.encryptButton.setGeometry(QtCore.QRect(430, 310, 151, 41))
        self.encryptButton.setObjectName(_fromUtf8("encryptButton"))
        self.layoutWidget_2 = QtGui.QWidget(self.tabEncrypt)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 310, 271, 41))
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.encGenerateKeyLayout = QtGui.QHBoxLayout(self.layoutWidget_2)
        self.encGenerateKeyLayout.setObjectName(_fromUtf8("encGenerateKeyLayout"))
        self.enc_gen_key_label = QtGui.QLabel(self.layoutWidget_2)
        self.enc_gen_key_label.setObjectName(_fromUtf8("enc_gen_key_label"))
        self.encGenerateKeyLayout.addWidget(self.enc_gen_key_label)
        self.enc_gen_key_button = QtGui.QPushButton(self.layoutWidget_2)
        self.enc_gen_key_button.setObjectName(_fromUtf8("enc_gen_key_button"))
        self.encGenerateKeyLayout.addWidget(self.enc_gen_key_button)
        self.widget = QtGui.QWidget(self.tabEncrypt)
        self.widget.setGeometry(QtCore.QRect(10, 160, 571, 131))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.encFileImportLayout = QtGui.QHBoxLayout(self.widget)
        self.encFileImportLayout.setObjectName(_fromUtf8("encFileImportLayout"))
        self.encLabelLayout = QtGui.QVBoxLayout()
        self.encLabelLayout.setObjectName(_fromUtf8("encLabelLayout"))
        self.enc_label_origin = QtGui.QLabel(self.widget)
        self.enc_label_origin.setMinimumSize(QtCore.QSize(71, 21))
        self.enc_label_origin.setObjectName(_fromUtf8("enc_label_origin"))
        self.encLabelLayout.addWidget(self.enc_label_origin)
        self.enc_label_key = QtGui.QLabel(self.widget)
        self.enc_label_key.setObjectName(_fromUtf8("enc_label_key"))
        self.encLabelLayout.addWidget(self.enc_label_key)
        self.enc_label_filepath = QtGui.QLabel(self.widget)
        self.enc_label_filepath.setObjectName(_fromUtf8("enc_label_filepath"))
        self.encLabelLayout.addWidget(self.enc_label_filepath)
        self.encFileImportLayout.addLayout(self.encLabelLayout)
        self.encAddressLayout = QtGui.QVBoxLayout()
        self.encAddressLayout.setObjectName(_fromUtf8("encAddressLayout"))
        self.encOriginFilePath = QtGui.QHBoxLayout()
        self.encOriginFilePath.setObjectName(_fromUtf8("encOriginFilePath"))
        self.enc_address_origin_text = QtGui.QLineEdit(self.widget)
        self.enc_address_origin_text.setMinimumSize(QtCore.QSize(371, 20))
        self.enc_address_origin_text.setObjectName(_fromUtf8("enc_address_origin_text"))
        self.encOriginFilePath.addWidget(self.enc_address_origin_text)
        self.enc_address_origin_button = QtGui.QPushButton(self.widget)
        self.enc_address_origin_button.setObjectName(_fromUtf8("enc_address_origin_button"))
        self.encOriginFilePath.addWidget(self.enc_address_origin_button)
        self.encAddressLayout.addLayout(self.encOriginFilePath)
        self.encBrowseKey = QtGui.QHBoxLayout()
        self.encBrowseKey.setObjectName(_fromUtf8("encBrowseKey"))
        self.enc_address_key_text = QtGui.QLineEdit(self.widget)
        self.enc_address_key_text.setMinimumSize(QtCore.QSize(371, 20))
        self.enc_address_key_text.setObjectName(_fromUtf8("enc_address_key_text"))
        self.encBrowseKey.addWidget(self.enc_address_key_text)
        self.enc_address_key_button = QtGui.QPushButton(self.widget)
        self.enc_address_key_button.setObjectName(_fromUtf8("enc_address_key_button"))
        self.encBrowseKey.addWidget(self.enc_address_key_button)
        self.encAddressLayout.addLayout(self.encBrowseKey)
        self.encEncFilePath = QtGui.QHBoxLayout()
        self.encEncFilePath.setObjectName(_fromUtf8("encEncFilePath"))
        self.enc_address_save_text = QtGui.QLineEdit(self.widget)
        self.enc_address_save_text.setMinimumSize(QtCore.QSize(371, 20))
        self.enc_address_save_text.setObjectName(_fromUtf8("enc_address_save_text"))
        self.encEncFilePath.addWidget(self.enc_address_save_text)
        self.enc_address_save_button = QtGui.QPushButton(self.widget)
        self.enc_address_save_button.setObjectName(_fromUtf8("enc_address_save_button"))
        self.encEncFilePath.addWidget(self.enc_address_save_button)
        self.encAddressLayout.addLayout(self.encEncFilePath)
        self.encFileImportLayout.addLayout(self.encAddressLayout)
        self.verticalLayoutWidget_4.raise_()
        self.enc_label_origin.raise_()
        self.enc_label_key.raise_()
        self.encryptButton.raise_()
        self.enc_label_filepath.raise_()
        self.enc_address_origin_text.raise_()
        self.enc_address_key_text.raise_()
        self.enc_address_save_text.raise_()
        self.enc_address_origin_button.raise_()
        self.enc_address_key_button.raise_()
        self.enc_address_save_button.raise_()
        self.layoutWidget_2.raise_()
        self.tab.addTab(self.tabEncrypt, _fromUtf8(""))
        self.tabDecrypt = QtGui.QWidget()
        self.tabDecrypt.setObjectName(_fromUtf8("tabDecrypt"))
        self.layoutWidget = QtGui.QWidget(self.tabDecrypt)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 160, 571, 131))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.decFileImportLayout = QtGui.QHBoxLayout(self.layoutWidget)
        self.decFileImportLayout.setObjectName(_fromUtf8("decFileImportLayout"))
        self.decLabelLayout = QtGui.QVBoxLayout()
        self.decLabelLayout.setObjectName(_fromUtf8("decLabelLayout"))
        self.dec_label_enc_filepath = QtGui.QLabel(self.layoutWidget)
        self.dec_label_enc_filepath.setMinimumSize(QtCore.QSize(71, 21))
        self.dec_label_enc_filepath.setObjectName(_fromUtf8("dec_label_enc_filepath"))
        self.decLabelLayout.addWidget(self.dec_label_enc_filepath)
        self.dec_label_key = QtGui.QLabel(self.layoutWidget)
        self.dec_label_key.setObjectName(_fromUtf8("dec_label_key"))
        self.decLabelLayout.addWidget(self.dec_label_key)
        self.dec_label_filepath = QtGui.QLabel(self.layoutWidget)
        self.dec_label_filepath.setObjectName(_fromUtf8("dec_label_filepath"))
        self.decLabelLayout.addWidget(self.dec_label_filepath)
        self.decFileImportLayout.addLayout(self.decLabelLayout)
        self.decAddressLayout = QtGui.QVBoxLayout()
        self.decAddressLayout.setObjectName(_fromUtf8("decAddressLayout"))
        self.decEncFilePath = QtGui.QHBoxLayout()
        self.decEncFilePath.setObjectName(_fromUtf8("decEncFilePath"))
        self.dec_address_enc_text = QtGui.QLineEdit(self.layoutWidget)
        self.dec_address_enc_text.setMinimumSize(QtCore.QSize(371, 20))
        self.dec_address_enc_text.setObjectName(_fromUtf8("dec_address_enc_text"))
        self.decEncFilePath.addWidget(self.dec_address_enc_text)
        self.dec_address_enc_button = QtGui.QPushButton(self.layoutWidget)
        self.dec_address_enc_button.setObjectName(_fromUtf8("dec_address_enc_button"))
        self.decEncFilePath.addWidget(self.dec_address_enc_button)
        self.decAddressLayout.addLayout(self.decEncFilePath)
        self.decBrowseKey = QtGui.QHBoxLayout()
        self.decBrowseKey.setObjectName(_fromUtf8("decBrowseKey"))
        self.dec_address_key_text = QtGui.QLineEdit(self.layoutWidget)
        self.dec_address_key_text.setMinimumSize(QtCore.QSize(371, 20))
        self.dec_address_key_text.setObjectName(_fromUtf8("dec_address_key_text"))
        self.decBrowseKey.addWidget(self.dec_address_key_text)
        self.dec_address_key_button = QtGui.QPushButton(self.layoutWidget)
        self.dec_address_key_button.setObjectName(_fromUtf8("dec_address_key_button"))
        self.decBrowseKey.addWidget(self.dec_address_key_button)
        self.decAddressLayout.addLayout(self.decBrowseKey)
        self.decDecFilePath = QtGui.QHBoxLayout()
        self.decDecFilePath.setObjectName(_fromUtf8("decDecFilePath"))
        self.dec_address_save_text = QtGui.QLineEdit(self.layoutWidget)
        self.dec_address_save_text.setMinimumSize(QtCore.QSize(371, 20))
        self.dec_address_save_text.setObjectName(_fromUtf8("dec_address_save_text"))
        self.decDecFilePath.addWidget(self.dec_address_save_text)
        self.dec_address_save_button = QtGui.QPushButton(self.layoutWidget)
        self.dec_address_save_button.setObjectName(_fromUtf8("dec_address_save_button"))
        self.decDecFilePath.addWidget(self.dec_address_save_button)
        self.decAddressLayout.addLayout(self.decDecFilePath)
        self.decFileImportLayout.addLayout(self.decAddressLayout)
        self.verticalLayoutWidget_5 = QtGui.QWidget(self.tabDecrypt)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(10, 20, 571, 111))
        self.verticalLayoutWidget_5.setObjectName(_fromUtf8("verticalLayoutWidget_5"))
        self.decAlgorithmsChose = QtGui.QVBoxLayout(self.verticalLayoutWidget_5)
        self.decAlgorithmsChose.setObjectName(_fromUtf8("decAlgorithmsChose"))
        self.dec_radio_des = QtGui.QRadioButton(self.verticalLayoutWidget_5)
        self.dec_radio_des.setObjectName(_fromUtf8("dec_radio_des"))
        self.decAlgorithmsChose.addWidget(self.dec_radio_des)
        self.dec_radio_aes = QtGui.QRadioButton(self.verticalLayoutWidget_5)
        self.dec_radio_aes.setObjectName(_fromUtf8("dec_radio_aes"))
        self.decAlgorithmsChose.addWidget(self.dec_radio_aes)
        self.dec_radio_rsa = QtGui.QRadioButton(self.verticalLayoutWidget_5)
        self.dec_radio_rsa.setObjectName(_fromUtf8("dec_radio_rsa"))
        self.decAlgorithmsChose.addWidget(self.dec_radio_rsa)
        self.decryptButton = QtGui.QPushButton(self.tabDecrypt)
        self.decryptButton.setGeometry(QtCore.QRect(430, 310, 151, 41))
        self.decryptButton.setObjectName(_fromUtf8("decryptButton"))
        self.tab.addTab(self.tabDecrypt, _fromUtf8(""))
        self.tab.raise_()
        self.enc_label_origin.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 620, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionGenerate_RSA_key = QtGui.QAction(MainWindow)
        self.actionGenerate_RSA_key.setObjectName(_fromUtf8("actionGenerate_RSA_key"))
        self.actionClose = QtGui.QAction(MainWindow)
        self.actionClose.setObjectName(_fromUtf8("actionClose"))
        self.actionRead_me = QtGui.QAction(MainWindow)
        self.actionRead_me.setObjectName(_fromUtf8("actionRead_me"))
        self.menuFile.addAction(self.actionGenerate_RSA_key)
        self.menuFile.addAction(self.actionClose)
        self.menuHelp.addAction(self.actionRead_me)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tab.setCurrentIndex(0)
        QtCore.QObject.connect(self.actionClose, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.close)
        QtCore.QObject.connect(self.enc_radio_des, QtCore.SIGNAL(_fromUtf8("clicked()")), self.enc_address_key_button.hide)
        QtCore.QObject.connect(self.enc_radio_rsa, QtCore.SIGNAL(_fromUtf8("clicked()")), self.enc_address_key_button.show)
        QtCore.QObject.connect(self.enc_radio_aes, QtCore.SIGNAL(_fromUtf8("clicked()")), self.enc_address_key_button.hide)
        QtCore.QObject.connect(self.dec_radio_aes, QtCore.SIGNAL(_fromUtf8("clicked()")), self.dec_address_key_button.hide)
        QtCore.QObject.connect(self.dec_radio_des, QtCore.SIGNAL(_fromUtf8("clicked()")), self.dec_address_key_button.hide)
        QtCore.QObject.connect(self.dec_radio_rsa, QtCore.SIGNAL(_fromUtf8("clicked()")), self.dec_address_key_button.show)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.enc_gen_key_button, self.tab)
        MainWindow.setTabOrder(self.tab, self.enc_radio_des)
        MainWindow.setTabOrder(self.enc_radio_des, self.enc_radio_aes)
        MainWindow.setTabOrder(self.enc_radio_aes, self.enc_radio_rsa)
        MainWindow.setTabOrder(self.enc_radio_rsa, self.enc_address_origin_text)
        MainWindow.setTabOrder(self.enc_address_origin_text, self.enc_address_origin_button)
        MainWindow.setTabOrder(self.enc_address_origin_button, self.enc_address_key_text)
        MainWindow.setTabOrder(self.enc_address_key_text, self.enc_address_key_button)
        MainWindow.setTabOrder(self.enc_address_key_button, self.enc_address_save_text)
        MainWindow.setTabOrder(self.enc_address_save_text, self.enc_address_save_button)
        MainWindow.setTabOrder(self.enc_address_save_button, self.encryptButton)
        MainWindow.setTabOrder(self.encryptButton, self.dec_radio_des)
        MainWindow.setTabOrder(self.dec_radio_des, self.dec_radio_aes)
        MainWindow.setTabOrder(self.dec_radio_aes, self.dec_radio_rsa)
        MainWindow.setTabOrder(self.dec_radio_rsa, self.dec_address_enc_text)
        MainWindow.setTabOrder(self.dec_address_enc_text, self.dec_address_enc_button)
        MainWindow.setTabOrder(self.dec_address_enc_button, self.dec_address_key_text)
        MainWindow.setTabOrder(self.dec_address_key_text, self.dec_address_key_button)
        MainWindow.setTabOrder(self.dec_address_key_button, self.dec_address_save_text)
        MainWindow.setTabOrder(self.dec_address_save_text, self.dec_address_save_button)
        MainWindow.setTabOrder(self.dec_address_save_button, self.decryptButton)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Simple Encrypt/Decrypt Program", None))
        self.enc_radio_des.setText(_translate("MainWindow", "DES algorithm", None))
        self.enc_radio_aes.setText(_translate("MainWindow", "AES algorithm", None))
        self.enc_radio_rsa.setText(_translate("MainWindow", "RSA algorithm", None))
        self.encryptButton.setText(_translate("MainWindow", "Encrypt", None))
        self.enc_gen_key_label.setText(_translate("MainWindow", "Not have key for RSA algorithm ?", None))
        self.enc_gen_key_button.setText(_translate("MainWindow", "Generate key", None))
        self.enc_label_origin.setText(_translate("MainWindow", "Origin file path   ", None))
        self.enc_label_key.setText(_translate("MainWindow", "Key", None))
        self.enc_label_filepath.setText(_translate("MainWindow", "Encrypt file path", None))
        self.enc_address_origin_button.setText(_translate("MainWindow", "browse ...", None))
        self.enc_address_key_button.setText(_translate("MainWindow", "browse ...", None))
        self.enc_address_save_button.setText(_translate("MainWindow", "browse ...", None))
        self.tab.setTabText(self.tab.indexOf(self.tabEncrypt), _translate("MainWindow", "ENCRYPT", None))
        self.dec_label_enc_filepath.setText(_translate("MainWindow", "Encrypt file path", None))
        self.dec_label_key.setText(_translate("MainWindow", "Key", None))
        self.dec_label_filepath.setText(_translate("MainWindow", "Decrypt file path", None))
        self.dec_address_enc_button.setText(_translate("MainWindow", "browse ...", None))
        self.dec_address_key_button.setText(_translate("MainWindow", "browse ...", None))
        self.dec_address_save_button.setText(_translate("MainWindow", "browse ...", None))
        self.dec_radio_des.setText(_translate("MainWindow", "DES algorithm", None))
        self.dec_radio_aes.setText(_translate("MainWindow", "AES algorithm", None))
        self.dec_radio_rsa.setText(_translate("MainWindow", "RSA algorithm", None))
        self.decryptButton.setText(_translate("MainWindow", "Decrypt", None))
        self.tab.setTabText(self.tab.indexOf(self.tabDecrypt), _translate("MainWindow", "DECRYPT", None))
        self.menuFile.setTitle(_translate("MainWindow", "File ", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.actionGenerate_RSA_key.setText(_translate("MainWindow", "Generate RSA key", None))
        self.actionClose.setText(_translate("MainWindow", "Close", None))
        self.actionRead_me.setText(_translate("MainWindow", "Read me!", None))

